apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: backend
type: Opaque
data:
  # Data needs to be converted to base64
  # MONGO_URI: mongodb://mongodb-service.database.svc.cluster.local:27017/tmmern
  MONGO_URI: bW9uZ29kYjovL2JXOXVaMjlrWWpvdkwyeHZZMkZzYUc5emREb3lOekF4Tnk5MGNtRjJaV3h0WlcxdmNuaz06MjcwMTcv
  # PORT: 3001
  PORT: MzAwMQ==
